#ifndef ASSETDIR_H
#define ASSETDIR_H

#define ASSET_DIR "../Assets"

#define MODEL_DIR "/Models"

#define SCENES_DIR ASSET_DIR "/Scenes"
#define SHADERS_DIR ASSET_DIR "/Shaders"
#define TEXTURES_DIR ASSET_DIR "/Textures"

#define TEXTURE_BILLBOARD_TEST TEXTURES_DIR "/BillboardTest.bmp"

#define SKYBOX_DIR TEXTURES_DIR "/Skybox"
#define SKYBOX_NIGHTSKY SKYBOX_DIR "/Nightsky"

#define SHEEP_DIR "/Sheep"
#define HOLY_SHEEP ASSET_DIR MODEL_DIR SHEEP_DIR "/SHEEP.obj"
#define HOLY_SHEEP_MATERIAL ASSET_DIR MODEL_DIR SHEEP_DIR "/"

#define WOLF_DIR "/Wolf"
#define HOLY_WOLF ASSET_DIR MODEL_DIR WOLF_DIR "/Wolf.obj"
#define HOLY_WOLF_MATERIAL ASSET_DIR MODEL_DIR WOLF_DIR "/"

#define UFO_DIR "/FlyingDisk"
#define HOLY_UFO ASSET_DIR MODEL_DIR UFO_DIR "/disk-flying.obj"
#define HOLY_UFO_MATERIAL ASSET_DIR MODEL_DIR UFO_DIR "/"

#define BUNNY_DIR "/Bunny"
#define HOLY_BUNNY ASSET_DIR MODEL_DIR BUNNY_DIR "/Bunny.obj"
#define HOLY_BUNNY_MATERIAL ASSET_DIR MODEL_DIR BUNNY_DIR "/"

#endif