#ifndef ASSETDIR_H
#define ASSETDIR_H

#define ASSET_DIR "../Assets"

#define MODEL_DIR "/Models"

#define SCENES_DIR ASSET_DIR "/Scenes"
#define SHADERS_DIR ASSET_DIR "/Shaders"
#define TEXTURES_DIR ASSET_DIR "/Textures"

#define TEXTURE_BILLBOARD_TEST TEXTURES_DIR "/BillboardTest.bmp"
#define TEXTURE_LOADING_MSG TEXTURES_DIR "/Loading.jpg"

#define SKYBOX_DIR TEXTURES_DIR "/Skybox"
#define SKYBOX_NIGHTSKY SKYBOX_DIR "/Nightsky"
#define SKYBOX_BLUESKY SKYBOX_DIR "/Bluesky"
#define SKYBOX_DUNES SKYBOX_DIR "/Dunes"

#define SHEEP_DIR "/Sheep"
#define HOLY_SHEEP ASSET_DIR MODEL_DIR SHEEP_DIR "/SHEEP.obj"
#define HOLY_SHEEP_MATERIAL ASSET_DIR MODEL_DIR SHEEP_DIR "/"

#define BUNNY_DIR "/Bunny"
#define HOLY_BUNNY ASSET_DIR MODEL_DIR BUNNY_DIR "/Bunny.obj"
#define HOLY_BUNNY_MATERIAL ASSET_DIR MODEL_DIR BUNNY_DIR "/"

#define UFO_DIR "/UFO"
#define HOLY_UFO ASSET_DIR MODEL_DIR UFO_DIR "/UFO.obj"
#define HOLY_UFO_MATERIAL ASSET_DIR MODEL_DIR UFO_DIR "/"

#define JET_DIR "/Jet"
#define HOLY_JET ASSET_DIR MODEL_DIR JET_DIR "/Jet.obj"
#define HOLY_JET_MATERIAL ASSET_DIR MODEL_DIR JET_DIR "/"

#define BARREL_DIR "/Barrel"
#define HOLY_BARREL ASSET_DIR MODEL_DIR BARREL_DIR "/Barrel.obj"
#define HOLY_BARREL_MATERIAL ASSET_DIR MODEL_DIR BARREL_DIR "/"
#endif