#include "FighterJetModel.h"
#include "AssetsDir.h"
#include "Animation.h"

using namespace std;
using namespace glm;

const glm::vec3 FighterJetModel::FIGHTER_JET_SHAPED_COLORS[] = {JET_COLOR, JET_COLOR2, JET_COLOR, JET_COLOR, JET_COLOR2, JET_COLOR2, JET_COLOR2, JET_COLOR2, JET_COLOR, JET_COLOR, JET_COLOR,
JET_COLOR, JET_COLOR2, JET_COLOR2, JET_COLOR2, JET_COLOR, JET_COLOR, JET_COLOR, JET_COLOR2, JET_COLOR2, JET_COLOR, JET_COLOR,
JET_COLOR2, JET_COLOR2, JET_COLOR2, JET_COLOR2, JET_COLOR2, JET_COLOR2, JET_COLOR2, JET_COLOR2, JET_COLOR2, JET_COLOR2, JET_COLOR2,
JET_COLOR2, JET_COLOR2, JET_COLOR2, JET_COLOR2, JET_COLOR2, JET_COLOR2, JET_COLOR2, JET_COLOR2, JET_COLOR2, JET_COLOR };

FighterJetModel::FighterJetModel() : ObjectModel(HOLY_JET, HOLY_JET_MATERIAL, FIGHTER_JET_SHAPED_COLORS)
{
}